-- DROP TABLE J31.DEPARTMENTS
CREATE TABLE J31.DEPARTMENTS(
DID INT PRIMARY KEY,
DNAME VARCHAR(20),
DLOC  VARCHAR(15),
DCODE VARCHAR(5)
)

-- INSERT NEW RECORD INTO DEPATRMENTS
INSERT INTO J31.DEPARTMENTS(DID, DNAME, DLOC, DCODE)VALUES(1,'Sales','Mumbai','CS001')
INSERT INTO J31.DEPARTMENTS(DID, DNAME, DLOC, DCODE)VALUES(2,'R AND D','BHOPAL','CS901')
INSERT INTO J31.DEPARTMENTS(DID, DNAME, DLOC, DCODE)VALUES(3,'MARKETING','INDORE','CS401');
INSERT INTO J31.DEPARTMENTS(DID, DNAME, DLOC, DCODE)VALUES(4,'PRODUCT','JABALPUR','CS031');
INSERT INTO J31.DEPARTMENTS(DID, DNAME, DLOC, DCODE)VALUES(5,'SUPPORT','GOA','CS081');
INSERT INTO J31.DEPARTMENTS(DID, DNAME, DLOC, DCODE)VALUES(6,'WORK','PUNE','CS481');

DELETE FROM J31.DEPARTMENTS WHERE DID=2
SELECT * FROM J31.DEPARTMENTS

CREATE TABLE J31.EMPLOYEES(
EMPID INT PRIMARY KEY,
ENAME VARCHAR(20),
DOJ  DATE DEFAULT(CURRENT_DATE),
DID INT,
FOREIGN KEY(DID)REFERENCES J31.DEPARTMENTS(DID)
) 

INSERT INTO  J31.EMPLOYEES(EMPID, ENAME, DID) VALUES (1, 'KOMAL','1')
INSERT INTO  J31.EMPLOYEES(EMPID, ENAME, DID)  VALUES (2, 'SMITA','1');
INSERT INTO  J31.EMPLOYEES(EMPID, ENAME, DID) VALUES (3, 'KAJAL','2');
INSERT INTO  J31.EMPLOYEES(EMPID, ENAME, DID) VALUES (4, 'SHALU','2');
INSERT INTO  J31.EMPLOYEES(EMPID, ENAME, DID) VALUES (5, 'KAMAL','3');
 INSERT INTO  J31.EMPLOYEES(EMPID, ENAME, DID) VALUES (6, 'LUCKY','4');
 INSERT INTO  J31.EMPLOYEES(EMPID, ENAME, DID) VALUES (7, 'RUMMY','5');
 
UPDATE J31.EMPLOYEES SET DID =4 WHERE EMPID = 2

